export default {
    name:"Ali Samiee",
    home:"HOME",
    about:"ABOUT",
    resume:"RESUME",
    portfolios:"PORTFOLIOS",
    contact:"CONTACT",
    hi:" Hi,I Am",
    hi2:"",
    desc:"I am a frontend web developer. I can provide clean code and pixel perfect design. I also make website more & more interactive with webanimations.",
    aboutme:"ABOUT ME",
    services:"SERVICES",
    fullname:"Full Name",
    age:"Age",
    nationality:"Nationality",
    Languages:"Languages",
    phone:"phone",
    years:"years",
    iranian:"Iranian",
    persian:"Persian",
    english:"English",
    download:"DownLoad CV",
    webdesign:"Web Design",
    mobileapp:"Mobile Application",
    webdep:"Web Development",
    servicedesc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",

    html:"HTML",
    react:"REACT JS",
    java:"JAVA SCRIPT",
    boot:"BOOTSTRAP",
    css:"CSS",
    python:"PYTHON",
    myskill:"MY SKILLS",
    resume:"RESUME",
    workingSteps : [
        { id: -1, date: "", title: "", subtitle: "", content: "" },
        {id: 0,date: "2018-2019",title: "Frontend Web Developer",subtitle: "Abc University", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"},
        {id: 1,date: "2018-2019",title: "Backend Web developer",subtitle: "Abc University", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}, 
        {id: 2,date: "2018-2019",title: "UI/UX Designer",subtitle: "Abc University", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}, 
        { id: -2, date: "", title: "", subtitle: "", content: "" },
      ],

      educationalSteps : [
        { id: -1, date: "", title: "", subtitle: "", content: "" },
        {id: 0,date: "2018-2019",title: "Master Of Science",subtitle: "Abc University", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"},
        {id: 1,date: "2018-2019",title: "Bachelor Of Science",subtitle: "Abc University", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}, 
        {id: 2,date: "2018-2019",title: "Highe School Graduation",subtitle: "Abc University", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}, 
        { id: -2, date: "", title: "", subtitle: "", content: "" },
      ],
      workingExperience: "Working Experience",
      Educational:"Educational Qualification",
      contactme:"CONTACT ME",
      getintouch:"Get In Touch",
      enteryourname:"Enter Your Name",
      enteryouremail:"Enter Your Email",
      enteryoursubject:"Enter Your Subject",
      enteryourmessage:"Enter Your Message",
      sendmessage:"Send Message",
      phone:"Phone",
      email:"Email",
      address:"Address",
      portfolios:"PORTFOLIOS",
      americancar:"American Car",



}

